spring:
  datasource:
    url: jdbc:mysql://23peopletest:3306/db_test
    username: test
    password: N0Tweak$_@123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
